"""Domain models for the Gold/Silver Trading System."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field, field_validator

from .enums import Bias, LockReason, Mode, Side, SignalStatus, Symbol, TradeOutcome


# ---------------------------------------------------------------------------
# Candle
# ---------------------------------------------------------------------------

class Candle(BaseModel):
    """A single OHLCV candle."""
    ts: datetime
    symbol: Symbol
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0


# ---------------------------------------------------------------------------
# Trade Idea / Signal
# ---------------------------------------------------------------------------

class TradeIdea(BaseModel):
    """A trading opportunity generated by the strategy engine."""
    id: int | None = None
    ts: datetime = Field(default_factory=datetime.utcnow)
    symbol: Symbol
    side: Side
    entry: float
    sl: float
    tp: float
    score: float = Field(ge=0, le=10, description="Setup quality score 0-10")
    reasons: list[str] = Field(default_factory=list)
    mode: Mode
    status: SignalStatus = SignalStatus.PENDING
    bias: Bias = Bias.NEUTRAL

    @field_validator("reasons", mode="before")
    @classmethod
    def parse_reasons(cls, v: Any) -> list[str]:
        if isinstance(v, str):
            try:
                return json.loads(v)
            except json.JSONDecodeError:
                return [v]
        return v

    @property
    def risk_reward(self) -> float:
        risk = abs(self.entry - self.sl)
        reward = abs(self.tp - self.entry)
        return round(reward / risk, 2) if risk > 0 else 0.0

    @property
    def risk_pips(self) -> float:
        return round(abs(self.entry - self.sl), 5)


# ---------------------------------------------------------------------------
# Trade Result
# ---------------------------------------------------------------------------

class TradeResult(BaseModel):
    """Record of an executed trade (paper or live)."""
    id: int | None = None
    signal_id: int | None = None
    ts_open: datetime = Field(default_factory=datetime.utcnow)
    ts_close: datetime | None = None
    symbol: Symbol
    side: Side
    entry: float
    sl: float
    tp: float
    size: float = 0.0
    outcome: TradeOutcome = TradeOutcome.OPEN
    pnl: float = 0.0
    mode: Mode = Mode.PAPER
    max_adverse_excursion: float = 0.0  # worst drawdown reached


# ---------------------------------------------------------------------------
# Risk State
# ---------------------------------------------------------------------------

class RiskState(BaseModel):
    """Daily risk tracking state."""
    date: str = ""
    trades_count: int = 0
    losses_count: int = 0
    pnl: float = 0.0
    drawdown_pct: float = 0.0
    locked_until_ts: datetime | None = None
    lock_reason: LockReason | None = None
    paused_until_ts: datetime | None = None
    kill_switch: bool = False

    @property
    def is_locked(self) -> bool:
        if self.kill_switch:
            return True
        if self.paused_until_ts and datetime.utcnow() < self.paused_until_ts:
            return True
        if self.locked_until_ts and datetime.utcnow() < self.locked_until_ts:
            return True
        return False


# ---------------------------------------------------------------------------
# Market Context (snapshot for analysis)
# ---------------------------------------------------------------------------

class MarketContext(BaseModel):
    """Aggregated market snapshot fed into the strategy engine."""
    symbol: Symbol
    ts: datetime = Field(default_factory=datetime.utcnow)
    bias: Bias = Bias.NEUTRAL
    price: float = 0.0
    spread: float = 0.0
    atr_15m: float = 0.0
    ema200_1h: float = 0.0
    ema20_15m: float = 0.0
    ema50_15m: float = 0.0
    rsi_15m: float = 50.0
    daily_high: float = 0.0
    daily_low: float = 0.0
    session_high: float = 0.0
    session_low: float = 0.0
    is_london_session: bool = False
    is_ny_session: bool = False
    volatility_regime: str = "normal"  # low | normal | high | extreme


# ---------------------------------------------------------------------------
# Setup / Scored Signal
# ---------------------------------------------------------------------------

class Setup(BaseModel):
    """A fully scored and validated trading setup."""
    context: MarketContext
    idea: TradeIdea
    score: float = 0.0
    reasons: list[str] = Field(default_factory=list)
    passed_filters: bool = True
    filter_failures: list[str] = Field(default_factory=list)
