"""Domain models for the Gold/Silver Trading System."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field, field_validator

from .enums import Bias, LockReason, Mode, Side, SignalStatus, Symbol, TradeOutcome


# ---------------------------------------------------------------------------
# Candle
# ---------------------------------------------------------------------------

class Candle(BaseModel):
    """A single OHLCV candle."""
    ts: datetime
    symbol: Symbol
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0


# ---------------------------------------------------------------------------
# Trade Idea / Signal
# ---------------------------------------------------------------------------

class TradeIdea(BaseModel):
    """A trading opportunity generated by the strategy engine."""
    id: int | None = None
    ts: datetime = Field(default_factory=datetime.utcnow)
    symbol: Symbol
    side: Side
    entry: float
    sl: float
    tp: float
    score: float = Field(ge=0, le=10, description="Setup quality score 0-10")
    reasons: list[str] = Field(default_factory=list)
    mode: Mode
    status: SignalStatus = SignalStatus.PENDING
    bias: Bias = Bias.NEUTRAL

    @field_validator("reasons", mode="before")
    @classmethod
    def parse_reasons(cls, v: Any) -> list[str]:
        if isinstance(v, str):
            try:
                return json.loads(v)
            except json.JSONDecodeError:
                return [v]
        return v

    @property
    def risk_reward(self) -> float:
        risk = abs(self.entry - self.sl)
        reward = abs(self.tp - self.entry)
        return round(reward / risk, 2) if risk > 0 else 0.0

    @property
    def risk_pips(self) -> float:
        return round(abs(self.entry - self.sl), 5)


# ---------------------------------------------------------------------------
# Trade Result
# ---------------------------------------------------------------------------

class TradeResult(BaseModel):
    """Record of an executed trade (paper or live)."""
    id: int | None = None
    signal_id: int | None = None
    ts_open: datetime = Field(default_factory=datetime.utcnow)
    ts_close: datetime | None = None
    symbol: Symbol
    side: Side
    entry: float
    sl: float
    tp: float
    size: float = 0.0
    outcome: TradeOutcome = TradeOutcome.OPEN
    pnl: float = 0.0
    mode: Mode = Mode.PAPER
    max_adverse_excursion: float = 0.0  # worst drawdown reached

    # ── Trade Journal fields (real broker only) ─────────────────────────────
    broker_position_id: str | None = None    # cTrader positionId
    broker_order_id: str | None = None       # cTrader orderId
    execution_latency_ms: int | None = None  # ms from order send → fill confirm
    entry_slippage: float | None = None      # fill_price − signal_entry (+ = worse)
    spread_at_entry: float | None = None     # ask − bid at time of execution
    exit_price: float | None = None          # actual close price from broker
    exit_slippage: float | None = None       # exit vs TP/SL price (+ = worse)


# ---------------------------------------------------------------------------
# Risk State
# ---------------------------------------------------------------------------

class RiskState(BaseModel):
    """Daily risk tracking state."""
    date: str = ""
    trades_count: int = 0
    losses_count: int = 0
    pnl: float = 0.0
    drawdown_pct: float = 0.0
    locked_until_ts: datetime | None = None
    lock_reason: LockReason | None = None
    paused_until_ts: datetime | None = None
    kill_switch: bool = False

    @property
    def is_locked(self) -> bool:
        if self.kill_switch:
            return True
        if self.paused_until_ts and datetime.utcnow() < self.paused_until_ts:
            return True
        if self.locked_until_ts and datetime.utcnow() < self.locked_until_ts:
            return True
        return False


# ---------------------------------------------------------------------------
# Market Context (snapshot for analysis)
# ---------------------------------------------------------------------------

class MarketContext(BaseModel):
    """Aggregated market snapshot fed into the strategy engine."""
    symbol: Symbol
    ts: datetime = Field(default_factory=datetime.utcnow)
    bias: Bias = Bias.NEUTRAL
    price: float = 0.0
    spread: float = 0.0
    atr_15m: float = 0.0
    ema200_1h: float = 0.0
    ema20_15m: float = 0.0
    ema50_15m: float = 0.0
    rsi_15m: float = 50.0
    daily_high: float = 0.0
    daily_low: float = 0.0
    session_high: float = 0.0
    session_low: float = 0.0
    is_london_session: bool = False
    is_ny_session: bool = False
    volatility_regime: str = "normal"  # low | normal | high | extreme


# ---------------------------------------------------------------------------
# Setup / Scored Signal
# ---------------------------------------------------------------------------

class Setup(BaseModel):
    """A fully scored and validated trading setup."""
    context: MarketContext
    idea: TradeIdea
    score: float = 0.0
    reasons: list[str] = Field(default_factory=list)
    passed_filters: bool = True
    filter_failures: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Expansion State  (Mode C)
# ---------------------------------------------------------------------------

class ExpansionState(BaseModel):
    """
    Tracks the Expansion Mode window for Mode C.

    Defensive mode is the default.  Expansion mode is activated only when
    statistical edge is proven and is automatically revoked when conditions
    deteriorate.
    """
    active: bool = False
    start_equity: float = 0.0           # equity when expansion was activated
    trades_in_window: int = 0           # trades taken since activation
    consecutive_losses: int = 0         # consecutive losses *within* this window
    activated_at: datetime | None = None
    exit_reason: str | None = None      # reason the last expansion window closed
    atr_spike_active: bool = False      # set True by market data layer on volatility event


# ---------------------------------------------------------------------------
# Account State
# ---------------------------------------------------------------------------

class AccountState(BaseModel):
    """
    Persistent account snapshot updated after every closed trade.

    - ``balance``            : current cash balance (starting_balance ± all closed PnL)
    - ``equity``             : current equity; for the demo engine this equals balance
                               (no open positions); a live engine would add unrealised PnL
    - ``peak_equity``        : highest equity ever reached (used for total drawdown)
    - ``equity_at_day_start``: equity recorded at the open of the current trading day
                               (used for the intraday drawdown hard stop)
    - ``drawdown_pct``       : (peak_equity - equity) / peak_equity * 100
    - ``total_pnl``          : cumulative PnL since account inception
    - ``consecutive_losses`` : current streak of consecutive losing trades; resets on any win
    """
    starting_balance: float = 10000.0
    balance: float = 10000.0
    equity: float = 10000.0
    peak_equity: float = 10000.0
    equity_at_day_start: float = 10000.0
    total_pnl: float = 0.0
    drawdown_pct: float = 0.0
    consecutive_losses: int = 0
    last_updated: datetime | None = None

    def apply_pnl(self, pnl: float) -> "AccountState":
        """Return a *new* AccountState with the PnL applied (immutable update)."""
        new_balance = round(self.balance + pnl, 2)
        new_equity = new_balance          # demo: equity == balance
        new_peak = max(self.peak_equity, new_equity)
        dd = round((new_peak - new_equity) / new_peak * 100, 4) if new_peak > 0 else 0.0
        new_consecutive = 0 if pnl >= 0 else self.consecutive_losses + 1
        return self.model_copy(update={
            "balance": new_balance,
            "equity": new_equity,
            "peak_equity": new_peak,
            "total_pnl": round(self.total_pnl + pnl, 2),
            "drawdown_pct": dd,
            "consecutive_losses": new_consecutive,
            "last_updated": datetime.utcnow(),
        })
